language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
script:
  - npm run test:prod && npm run build

jobs:
  include:
    - stage: report_coverage
      script: npm run report-coverage
    - stage: deploy_docs
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy-docs; fi
    - stage: npm_release
      script: if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
